= Examples
:page-topic-type: concept

WARNING: Please note that the examples below will alter the data in your sample buckets.
To restore your sample data, remove and reinstall the `travel-sample` bucket.
Refer to xref:manage:manage-settings/install-sample-buckets.adoc[Sample Buckets] for details.

== Example1

Here is an example of aggregating using correlated subquery expression in projection.
This query finds the top 3 overall rated hotels.
The subquery in the projection finds the average overall rating across all rating of the given hotel document `t`.

[source,n1ql]
----
SELECT name, (SELECT raw avg(s.ratings.Overall)
              FROM   t.reviews  as s)[0] AS overall_avg_rating
FROM   `travel-sample`.inventory.hotel AS t
ORDER BY overall_avg_rating DESC
LIMIT 3;
----
.Results
[source,json]
----
  {
    "name": "Culloden House Hotel",
  },
  {
    "name": "The Bulls Head",
    "overall_avg_rating": 5
  },
  {
    "name": "La Pradella",
    "overall_avg_rating": 5
  }
]
----



In the above example, the subquery is used as a part of WHERE condition of the parent query and it returns an array of cities that have airports.

Note that the IN or WITHIN predicate needs an array on right-side expression as the subquery evaluates to.
Further, the usage of keyword `RAW` in the subquery projection ensures just the `city` attribute values in the result without JSON wrapping.
The outer query browses through each of the landmark cities and returns the city name if it is in the array of cities returned by the inner subquery.

When subquery is used in the FROM clause, that must be aliased, to be able to access and refer to the results documents of the subquery.
In the following example <<Q2,Q2>>, the subquery is named as `t1`, and it returns the aggregated value of airport names by city and country.
The outer query further processes the result of the subquery to find total number of airports by country where each city has more than 5 airports.

Example Q2:

[source#Q2,n1ql]
----
DELETE FROM `travel-sample`.inventory.hotel
WHERE city = "San Francisco"
RETURNING meta().id;  
----
.Results:
[source,json]
----
[
  {
    "$1": [
      "Paris"
    ],
    "apnum": 9,
    "country": "France"
  },
  {
    "$1": [
      "London"
    ],
    "apnum": 13,
    "country": "United Kingdom"
  },
  {
    "$1": [
      "Houston",
      "New York",
      "San Diego"
    ],
    "apnum": 22,
    "country": "United States"
  }
]
----

For more examples, see the <<section_cjh_pck_mz,Examples>> section.

[#subquery-n1ql-exp]
== Subqueries in N1QL Expressions

Subqueries can appear as independent SELECT queries or can be combined as a constituent part of other N1QL language expressions.

For example, in the above queries <<Q1,Q1>> and <<Q2,Q2>>, the subquery is a full independent SELECT query.
In the following example <<Q3,Q3>>, the subquery is part of a N1QL expression.

Example Q3:
[source#Q3,n1ql]
----
UPDATE `travel-sample`.inventory.route t
USE KEYS "route_10003"
SET s.codeshare = NULL FOR s IN schedule END
RETURNING t;
----
.Results:
[source,json]
----
[
  {
    "$1": 14
  }
]
----

== Example 5

This example shows usage of subquery expressions in MERGE statement.
This query uses constant expression as the MERGE source data, and updates the vacancy to false for matching documents.
For the sake of demonstrating update operation, this query saves the current value of vacancy to a new attribute old_vacancy.

[source,n1ql]
----
MERGE INTO `travel-sample`.inventory.hotel t USING [{"id":"21728"},{"id":"21730"}] source
ON KEY "hotel_"|| source.id
WHEN MATCHED THEN UPDATE SET t.old_vacancy = t.vacancy, t.vacancy = false
RETURNING meta(t).id, t.old_vacancy, t.vacancy;
----

.Results:
[source,json]
----
[
  {
    "id": "hotel_21728",
    "old_vacancy": false,
    "vacancy": false
  },
  {
    "id": "hotel_21730",
    "old_vacancy": true,
    "vacancy": false
  }
]
----
== Example 12

A non-correlated subquery with INSERT.

[source,n1ql]
----
INSERT INTO `travel-sample`.inventory.hotel (KEY UUID()) 
    SELECT x.name, x.city, "landmark_hotels" AS type 
      FROM `travel-sample`.inventory.hotel x
      WHERE x.city WITHIN
        ( SELECT DISTINCT t.city 
            FROM `travel-sample`.inventory.landmark t)
      LIMIT 4
RETURNING *;
----

.Results
[source,json]
----
[
  {
    "hotel": {
      "city": "Aberdeenshire",
      "name": "Castle Hotel",
      "type": "landmark_hotels"
    }
  },
  {
    "hotel": {
      "city": "Aberdeenshire",
      "name": "Two Bears Cottage",
      "type": "landmark_hotels"
    }
  },
  {
    "hotel": {
      "city": "Agoura Hills",
      "name": "Malibu Creek Campground",
      "type": "landmark_hotels"
    }
  },
  {
    "hotel": {
      "city": "Altrincham",
      "name": "Cresta Court Hotel",
      "type": "landmark_hotels"
    }
  }
]
----